# Generated by Django 5.0.6 on 2024-05-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('username', models.TextField()),
                ('phone_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NGO_name', models.CharField(max_length=100)),
                ('Registration_number', models.IntegerField()),
                ('Year_of_registration', models.IntegerField()),
                ('website', models.CharField(max_length=100)),
                ('NGO_type', models.TextField()),
                ('office_address', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=100)),
                ('Terms', models.BooleanField(default=False)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Legal_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('terms', models.BooleanField(default=False)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='Celeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('entertainment_category', models.CharField(choices=[('Music', 'Music'), ('Actor/Actress', 'Actor/Actress'), ('Comedy', 'Comedy'), ('Standup Artist', 'Standup Artist')], default='Music', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('USA', 'USA'), ('South Africa', 'South Africa'), ('Canada', 'Canada'), ('Australia', 'Australia')], default='Nigeria', max_length=20)),
                ('face_book_name', models.TextField()),
                ('X_handle', models.TextField()),
                ('Insta_handle', models.TextField()),
                ('verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userlogin')),
            ],
        ),
    ]
