# Generated by Django 5.0.6 on 2024-05-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celeb',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='fans',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='login_id',
        ),
    ]
