# Generated by Django 3.2.3 on 2024-05-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_celeb_login_id_remove_fans_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fans',
            name='Fan_of',
            field=models.CharField(default='ay', max_length=100),
        ),
    ]
