# Generated by Django 3.2.3 on 2024-05-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_fans_fan_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fans',
            name='Fan_of',
            field=models.CharField(choices=[('davido', 'davido'), ('ay', 'ay'), ('seyi_law', 'seyi_law')], default='ay', max_length=100),
        ),
    ]
