# Generated by Django 3.2.3 on 2024-05-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_fans_fan_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fans',
            name='Fan_of',
        ),
        migrations.RemoveField(
            model_name='fans',
            name='Legal_name',
        ),
        migrations.RemoveField(
            model_name='fans',
            name='country',
        ),
        migrations.RemoveField(
            model_name='fans',
            name='terms',
        ),
        migrations.AddField(
            model_name='fans',
            name='fan_of',
            field=models.CharField(choices=[('davido', 'Davido'), ('ay', 'Ay'), ('seyi_law', 'Seyi Law')], default='ay', max_length=255),
        ),
    ]
