# Generated by Django 3.2.3 on 2024-05-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20240519_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fans',
            name='fan_of',
        ),
        migrations.AddField(
            model_name='fans',
            name='Fan_of',
            field=models.CharField(choices=[('davido', 'davido'), ('ay', 'ay'), ('seyi_law', 'seyi_law')], default='ay', max_length=100),
        ),
        migrations.AddField(
            model_name='fans',
            name='Legal_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fans',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fans',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
